services:
  retrieval:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retrieval-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always